# Generated by Django 3.0.2 on 2020-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmmaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('type_of_filmmaker', models.IntegerField(choices=[(0, 'DIRECTOR'), (1, 'PRODUCTOR')], default=0, verbose_name='Director / Productor')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del planeta')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Población mundial')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la película')),
                ('description', models.CharField(max_length=150, verbose_name='Sinópsis')),
                ('published_at', models.DateField(verbose_name='Fecha de publicación')),
                ('filmmakers', models.ManyToManyField(to='api.Filmmaking')),
                ('planets', models.ManyToManyField(to='api.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('movies', models.ManyToManyField(to='api.Movie')),
            ],
        ),
    ]
