# Generated by Django 3.0.2 on 2020-07-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('m', 'MASCÚLINO'), ('f', 'FEMENINO')], default='m', max_length=5, verbose_name='Género / Sexo'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(default='N/A', max_length=150, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_of_birth',
            field=models.CharField(max_length=50, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Sinópsis'),
        ),
    ]
